mysql:
  adapter: mysql
  database: delayed_job_test
  username: delayed_job
  encoding: utf8

postgresql:
  adapter: postgresql
  database: delayed_job_test
  username: postgres

sqlite3:
  adapter: sqlite3
  database: ":memory:"
